#pragma once
#include "mem.h"
#include <xmmintrin.h>
#include <intrin.h>
#include <Windows.h>
#include <stdint.h>
#include "Vector3.h"
#include <list>

enum EBones : int
{
    None11 = 0,
    IKController,
    Mesh,
    Vest_0,
    Vest_1,
    backpack,
    backpack_0,
    backpack_1,
    backpack_2,
    razgruz,
    razgruz_0,
    razgruz_1,
    razgruz_2,
    Root_Joint,
    Pelvis,
    LThigh1,
    LThigh2,
    LCalf,
    LFoot,
    LToe,
    RThigh1,
    RThigh2,
    RCalf,
    RFoot,
    RToe,
    Bear_Feet,
    USEC_Feet,
    BEAR_feet_1,
    weapon_holster_pistol,
    Spine1,
    Gear1,
    Gear2,
    Gear3,
    Gear4,
    Gear4_1,
    Gear5,
    Spine2,
    Spine3,
    IK_S_LForearm1,
    IK_S_LForearm2,
    IK_S_LForearm3,
    IK_S_LPalm,
    IK_S_LDigit11,
    IK_S_LDigit12,
    IK_S_LDigit13,
    IK_S_LDigit21,
    IK_S_LDigit22,
    IK_S_LDigit23,
    IK_S_LDigit31,
    IK_S_LDigit32,
    IK_S_LDigit33,
    IK_S_LDigit41,
    IK_S_LDigit42,
    IK_S_LDigit43,
    IK_S_LDigit51,
    IK_S_LDigit52,
    IK_S_LDigit53,
    XYZ,
    LCollarbone_anim,
    RCollarbone_anim,
    RCollarbone_anim_XYZ,
    Weapon_root_3rd_anim,
    XYZ_1,
    Bend_Goal_Left,
    Bend_Goal_Right,
    Bend_Goal_Right_XYZ_1,
    Ribcage,
    IK_LForearm1,
    IK_LForearm2,
    IK_LForearm3,
    IK_LPalm,
    IK_LDigit11,
    IK_LDigit12,
    IK_LDigit13,
    IK_LDigit21,
    IK_LDigit22,
    IK_LDigit23,
    IK_LDigit31,
    IK_LDigit32,
    IK_LDigit33,
    IK_LDigit41,
    IK_LDigit42,
    IK_LDigit43,
    IK_LDigit51,
    IK_LDigit52,
    IK_LDigit53,
    Camera_animated,
    CameraContainer,
    Cam,
    LCollarbone,
    LUpperarm,
    LForearm1,
    LForearm2,
    LForearm3,
    LPalm,
    LDigit11,
    LDigit12,
    LDigit13,
    LDigit21,
    LDigit22,
    LDigit23,
    LDigit31,
    LDigit32,
    LDigit33,
    LDigit41,
    LDigit42,
    LDigit43,
    LDigit51,
    LDigit52,
    LDigit53,
    RCollarbone,
    RUpperarm,
    RForearm1,
    RForearm2,
    RForearm3,
    RPalm,
    RDigit11,
    RDigit12,
    RDigit13,
    RDigit21,
    RDigit22,
    RDigit23,
    RDigit31,
    RDigit32,
    RDigit33,
    RDigit41,
    RDigit42,
    RDigit43,
    RDigit51,
    RDigit52,
    RDigit53,
    Weapon_root,
    Neck,
    Head,
    Backpack,
    weapon_holster,
    weapon_holster1,
    Camera_animated_3rd
};
std::initializer_list<std::initializer_list<EBones>> EBoneConnections =
{
    {EBones::Pelvis, EBones::LThigh1},
    {EBones::LThigh1, EBones::LThigh2},
    {EBones::LThigh2, EBones::LCalf},
    {EBones::LCalf, EBones::LFoot},
    {EBones::LFoot, EBones::LToe},
    {EBones::Pelvis, EBones::RThigh1},
    {EBones::RThigh1, EBones::RThigh2},
    {EBones::RThigh2, EBones::RCalf},
    {EBones::RCalf, EBones::RFoot},
    {EBones::RFoot, EBones::RToe},
    {EBones::Pelvis, EBones::Spine1},
    {EBones::Spine1, EBones::Spine2},
    {EBones::Spine2, EBones::Spine3},
    {EBones::Spine3, EBones::Neck},
    {EBones::Neck, EBones::Head},
    {EBones::Spine3, EBones::LCollarbone},
    {EBones::LCollarbone, EBones::LForearm1},
    {EBones::LForearm1, EBones::LForearm2},
    {EBones::LForearm2, EBones::LForearm3},
    {EBones::LForearm3, EBones::LPalm},
    {EBones::LPalm, EBones::LDigit11},
    {EBones::LDigit11, EBones::LDigit12},
    {EBones::LDigit12, EBones::LDigit13},
    {EBones::LPalm, EBones::LDigit21},
    {EBones::LDigit21, EBones::LDigit22},
    {EBones::LDigit22, EBones::LDigit23},
    {EBones::LPalm, EBones::LDigit31},
    {EBones::LDigit31, EBones::LDigit32},
    {EBones::LDigit32, EBones::LDigit33},
    {EBones::LPalm, EBones::LDigit41},
    {EBones::LDigit41, EBones::LDigit42},
    {EBones::LDigit42, EBones::LDigit43},
    {EBones::LPalm, EBones::LDigit51},
    {EBones::LDigit51, EBones::LDigit52},
    {EBones::LDigit52, EBones::LDigit53},
    {EBones::Spine3, EBones::RCollarbone},
    {EBones::RCollarbone, EBones::RForearm1},
    {EBones::RForearm1, EBones::RForearm2},
    {EBones::RForearm2, EBones::RForearm3},
    {EBones::RForearm3, EBones::RPalm},
    {EBones::RPalm, EBones::RDigit11},
    {EBones::RDigit11, EBones::RDigit12},
    {EBones::RDigit12, EBones::RDigit13},
    {EBones::RPalm, EBones::RDigit11},
    {EBones::RDigit21, EBones::RDigit22},
    {EBones::RDigit22, EBones::RDigit23},
    {EBones::RPalm, EBones::RDigit11},
    {EBones::RDigit31, EBones::RDigit32},
    {EBones::RDigit32, EBones::RDigit33},
    {EBones::RPalm, EBones::RDigit11},
    {EBones::RDigit41, EBones::RDigit42},
    {EBones::RDigit42, EBones::RDigit43},
    {EBones::RPalm, EBones::RDigit11},
    {EBones::RDigit51, EBones::RDigit52},
    {EBones::RDigit52, EBones::RDigit53}
};
std::list<int> upper_part = { EBones::Neck, EBones::Head, EBones::Head };
std::list<int> right_arm = { EBones::Neck, EBones::RUpperarm, EBones::RForearm2, EBones::RPalm };
std::list<int> left_arm = { EBones::Neck, EBones::LUpperarm, EBones::LForearm2, EBones::LPalm };
std::list<int> spine = { EBones::Neck, EBones::Spine2, EBones::Spine3, EBones::Pelvis };
std::list<int> lower_right = { EBones::Pelvis, EBones::RThigh1, EBones::RCalf, EBones::RFoot };
std::list<int> lower_left = { EBones::Pelvis, EBones::LThigh1, EBones::LCalf, EBones::LFoot };
std::list<std::list<int>> skeletons = { upper_part, right_arm, left_arm, spine, lower_right, lower_left };

std::initializer_list<std::initializer_list<EBones>> EBoneConnectionsSample =
{
    {EBones::Head,      EBones::Neck},
    //”“±ﬂ ÷±€
    {EBones::Neck,      EBones::RUpperarm},
    {EBones::RUpperarm, EBones::RForearm2},
    {EBones::RForearm2, EBones::RPalm},
    //◊Û±ﬂ ÷±€
    {EBones::Neck,      EBones::LUpperarm},
    {EBones::LUpperarm, EBones::LForearm2},
    {EBones::LForearm2, EBones::LPalm},
    //ºπ¡∫
    {EBones::Pelvis,    EBones::Spine1},
    {EBones::Spine1,    EBones::Spine2},
    {EBones::Spine2,    EBones::Spine3},
    {EBones::Spine3,    EBones::Neck},
    //”“Õ»
    {EBones::Pelvis,    EBones::RThigh1},
    {EBones::RThigh1,   EBones::RCalf},
    {EBones::RCalf,     EBones::RFoot},
    //◊ÛÕ»
    {EBones::Pelvis,    EBones::LThigh1},
    {EBones::LThigh1,   EBones::LCalf},
    {EBones::LCalf,     EBones::LFoot},
};